apiVersion: integrations.sdk.management.ibm.com/v1beta1
kind: OidcClientRegistration
metadata:
  name: turbonomic-mcm-demo
spec:
  registration:
    post_logout_redirect_uris:
      - https://api-turbonomic.{{ .OpenShiftBaseUrl }}/app/index.html
    trusted_uri_prefixes:
      - https://api-turbonomic.{{ .OpenShiftBaseUrl }}
    redirect_uris:
      - https://api-turbonomic.{{ .OpenShiftBaseUrl }}/vmturbo/oauth2/login/code/ibm
    client_secret:
      secretName: turbonomic-mcm-demo
      secretKey: YourSecret
    apply_client_secret: true
