{{- if .Values.ingress.enabled -}}
{{- $serviceName := include "fullname" . -}}
{{- $servicePort := .Values.service.externalPort -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    inmenu: "{{ .Values.service.uiMenu.enabled }}" # NavMenu: Enable visibility in menu
  annotations: # NavMenu: add annotations from values.yaml
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    - http:
        paths:
          - path: /vmturbo/oauth2/authorization/ibm
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
          - path: /app/index.html
            backend:
              serviceName: {{ $serviceName }}-app
              servicePort: {{ $servicePort }}
          - path: /assets
            backend:
              serviceName: {{ $serviceName }}-assets
              servicePort: {{ $servicePort }}
          - path: /doc
            backend:
              serviceName: {{ $serviceName }}-doc
              servicePort: {{ $servicePort }}
          - path: /vmturbo
            backend:
              serviceName: {{ $serviceName }}-api
              servicePort: {{ $servicePort }}
  {{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}
